const char AFTER_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Success</title>\n"
"    <style>\n"
"        * {\n"
"            padding: 0;\n"
"            margin: 0;\n"
"            box-sizing: border-box;\n"
"        }\n"
"\n"
"        /* label text to be aligned to the left */\n"
"        form#wifi-details label {\n"
"            align-self: flex-start;\n"
"        }\n"
"\n"
"        /* common flex styles */\n"
"        .login,\n"
"        .login-card,\n"
"        form#wifi-details,\n"
"        .data-input {\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"        }\n"
"\n"
"        .login {\n"
"            background-color: hsl(350, 100%, 88%);\n"
"            height: 100vh;\n"
"            width: 100%;\n"
"\n"
"            font-family: 'Poppins', sans-serif;\n"
"        }\n"
"\n"
"        .login-card {\n"
"            background: rgba(255, 255, 255, 0.75);\n"
"            height: 100vh;\n"
"            width: 33rem;\n"
"            border-radius: 1rem;\n"
"            z-index: 10;\n"
"\n"
"            justify-content: space-evenly;\n"
"        }\n"
"\n"
"        .login-card-heading {\n"
"            font-style: italic;\n"
"            text-transform: capitalize;\n"
"            font-weight: 600;\n"
"        }\n"
"\n"
"        form#wifi-details {\n"
"            height: 55%;\n"
"            justify-content: space-evenly;\n"
"        }\n"
"\n"
"        .data-input {\n"
"            justify-content: flex-start;\n"
"        }\n"
"\n"
"        input {\n"
"            padding: 0 1.5rem;\n"
"            background: #FFFFFF;\n"
"            border: 1px solid #ADADAD;\n"
"            box-sizing: border-box;\n"
"            border-radius: 9px;\n"
"            height: 3rem;\n"
"        }\n"
"\n"
"        button#submit-details {\n"
"            margin: 1rem;\n"
"            height: 3rem;\n"
"            background-color: #2f80ed;\n"
"            box-shadow: 0 4px 19px #80a8de;\n"
"            border-style: none;\n"
"            border-radius: 10px;\n"
"            color: white;\n"
"            width: 12rem;\n"
"            cursor: pointer;\n"
"        }\n"
"\n"
"        .house {\n"
"            position: relative;\n"
"            width: 0px;\n"
"            height: 0px;\n"
"            box-sizing: content-box;\n"
"\n"
"            border-left: 60px solid transparent;\n"
"            border-right: 60px solid transparent;\n"
"            border-bottom: 50px solid hsl(350, 100%, 88%);\n"
"        }\n"
"\n"
"        .house:before,\n"
"        .house:after {\n"
"            content: \"\";\n"
"            box-sizing: content-box;\n"
"            position: absolute;\n"
"            background-color: hsl(350, 100%, 88%);\n"
"        }\n"
"\n"
"        .house:before {\n"
"            width: 10px;\n"
"            height: 30px;\n"
"            top: 20px;\n"
"            left: 30px;\n"
"        }\n"
"\n"
"        .house:after {\n"
"            width: 100px;\n"
"            height: 60px;\n"
"            top: 50px;\n"
"            left: -50px;\n"
"        }\n"
"\n"
"        @media (max-width:768px) {\n"
"            .login {\n"
"                border-radius: 1rem;\n"
"            }\n"
"\n"
"            .login-card {\n"
"                height: 100vh;\n"
"                width: 100%;\n"
"            }\n"
"        }\n"
"\n"
"    </style>\n"
"</head>\n"
"\n"
"<body onload=\"callTimerFunc()\">\n"
"    <script>\n"
"        function timer(time, update, complete) {\n"
"            var start = new Date().getTime();\n"
"            var interval = setInterval(function () {\n"
"                var now = time - (new Date().getTime() - start);\n"
"                if (now <= 0) {\n"
"                    clearInterval(interval);\n"
"                    complete();\n"
"                }\n"
"                else update(Math.floor(now / 1000));\n"
"            }, 100); // the smaller this number, the more accurate the timer will be\n"
"        }\n"
"\n"
"        function callTimerFunc() {\n"
"            timer(\n"
"                4000, // milliseconds\n"
"                function (timeleft) { // called every step to update the visible countdown\n"
"                    document.getElementById('timer').innerHTML = timeleft;\n"
"                },\n"
"                () => { }\n"
"            );\n"
"        }\n"
"\n"
"    </script>\n"
"    <div class=\"login\">\n"
"        <div class=\"login-card\">\n"
"            <div class=\"house\"></div>\n"
"\n"
"            <div class=\"login-card-heading\">\n"
"                <span>Success!</span>\n"
"            </div>\n"
"\n"
"            <div>\n"
"                <span>Device will restart in <span id=\"timer\">3</span> second(s)</span>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"</body>\n"
"\n"
"</html>\n"
""
"";
